/**
 * Wrexlyn for Investments license-server — Copyright (c) 2026 Nishant Prabhakar. All rights reserved.
 * See LICENSE for details.
 *
 * Token generation/hashing and HTML escaping shared by the API and admin routes.
 */
import * as crypto from "crypto";

/** A high-entropy bearer token handed to a device on register — never stored raw. */
export function generateToken(bytes = 32): string {
  return crypto.randomBytes(bytes).toString("hex");
}

/**
 * SHA-256, not bcrypt: this hashes 256 bits of random entropy generated by this
 * server itself, not a low-entropy user-chosen password — bcrypt's deliberate
 * slowness defends against brute-forcing a small guessable keyspace, which doesn't
 * apply here and would just add needless latency to every checkin.
 */
export function hashToken(token: string): string {
  return crypto.createHash("sha256").update(token, "utf-8").digest("hex");
}

/** Constant-time comparison for the admin session cookie / password check. */
export function safeEqual(a: string, b: string): boolean {
  const bufA = Buffer.from(a, "utf-8");
  const bufB = Buffer.from(b, "utf-8");
  if (bufA.length !== bufB.length) return false;
  return crypto.timingSafeEqual(bufA, bufB);
}

const HTML_ESCAPES: Record<string, string> = {
  "&": "&amp;",
  "<": "&lt;",
  ">": "&gt;",
  '"': "&quot;",
  "'": "&#39;",
};

/**
 * Every admin-rendered field that ever contains user-supplied input (name, email,
 * revoke reason) MUST go through this before being interpolated into HTML — a user
 * registering with a `name` containing `<script>` must not become stored XSS
 * against the admin's own session. See __tests__/tokens.test.ts for the regression
 * test asserting this specifically.
 */
export function escapeHtml(value: string): string {
  return value.replace(/[&<>"']/g, (ch) => HTML_ESCAPES[ch]);
}
